VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

VIAL_INSECURE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
