VIA_ENABLE = yes
VIAL_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
VIALRGB_ENABLE = yes

RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
QMK_SETTINGS = no
